### ISSUE TITLE
the error ???

### ISSUE THREAD

**Issue by felayman** [michaellavelle/spring-data-dynamodb#74] opened 2016-01-07 11:37 UTC
the code is :
package com.vcg.community.kafka.data.api.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

/**
- @author felayman
- @since 16/1/7
  */
  @DynamoDBTable(tableName = "vcg-activity-master-test")
  public class Entity  implements Serializable{
  
  private static final long serialVersionUID = 7736584783601772126L;
  
  private String mainTypeId;
  private String relativeTypeId;
  private long eventTimestamp;
  private String eventDate;
  private boolean isDeleted;
  private String itemType;
  private String ownerType;
  private String ownerId;
  private String relativeType;
  private String relativeId;
  private String properties;
  
  @DynamoDBHashKey(attributeName = "main_type-id")
  public String getMainTypeId() {
      return mainTypeId;
  }
  
  public void setMainTypeId(String mainTypeId) {
      this.mainTypeId = mainTypeId;
  }
  
  @DynamoDBRangeKey(attributeName = "related_type-id")
  public String getRelativeTypeId() {
      return relativeTypeId;
  }
  
  public void setRelativeTypeId(String relativeTypeId) {
      this.relativeTypeId = relativeTypeId;
  }
  
  @DynamoDBAttribute(attributeName = "event_timestamp")
  public long getEventTimestamp() {
      return eventTimestamp;
  }
  
  public void setEventTimestamp(long eventTimestamp) {
      this.eventTimestamp = eventTimestamp;
  }
  
  @DynamoDBAttribute(attributeName = "event_date")
  public String getEventDate() {
      return eventDate;
  }
  
  public void setEventDate(String eventDate) {
      this.eventDate = eventDate;
  }
  
  @DynamoDBAttribute(attributeName = "is_deleted")
  public boolean isDeleted() {
      return isDeleted;
  }
  
  public void setDeleted(boolean deleted) {
      isDeleted = deleted;
  }
  
  @DynamoDBAttribute(attributeName = "item_type")
  public String getItemType() {
      return itemType;
  }
  
  public void setItemType(String itemType) {
      this.itemType = itemType;
  }
  
  @DynamoDBAttribute(attributeName = "owner_type")
  public String getOwnerType() {
      return ownerType;
  }
  
  public void setOwnerType(String ownerType) {
      this.ownerType = ownerType;
  }
  
  @DynamoDBAttribute(attributeName = "owner_id")
  public String getOwnerId() {
      return ownerId;
  }
  
  public void setOwnerId(String ownerId) {
      this.ownerId = ownerId;
  }
  
  @DynamoDBAttribute(attributeName = "related_type")
  public String getRelativeType() {
      return relativeType;
  }
  
  public void setRelativeType(String relativeType) {
      this.relativeType = relativeType;
  }
  
  @DynamoDBAttribute(attributeName = "related_id")
  public String getRelativeId() {
      return relativeId;
  }
  
  public void setRelativeId(String relativeId) {
      this.relativeId = relativeId;
  }
  
  @DynamoDBAttribute(attributeName = "properties")
  public String getProperties() {
      return properties;
  }
  
  public void setProperties(String properties) {
      this.properties = properties;
  }
  
  @Override
  public String toString() {
      return "Entity{" +
              "mainTypeId='" + mainTypeId + '\'' +
              ", relativeTypeId='" + relativeTypeId + '\'' +
              ", eventTimestamp=" + eventTimestamp +
              ", eventDate='" + eventDate + '\'' +
              ", isDeleted=" + isDeleted +
              ", itemType='" + itemType + '\'' +
              ", ownerType='" + ownerType + '\'' +
              ", ownerId='" + ownerId + '\'' +
              ", relativeType='" + relativeType + '\'' +
              ", relativeId='" + relativeId + '\'' +
              ", properties='" + properties + '\'' +
              '}';
  }
  }

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No field annotated with interface org.springframework.data.annotation.Id found!

how  should i deal the error ?

**Comment by derjust** [comment] 2016-01-07 14:26
How does your `Repository` class looks like?
(Please use some [code formatting](https://guides.github.com/features/mastering-markdown/#code) for improved readability)

**Comment by derjust** [comment] 2016-01-25 03:11
Please provide more information / answer to the question above at https://github.com/derjust/spring-data-dynamodb/issues/24.

As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.

**Comment by rwhitsell** [comment] 2016-04-13 04:46
I've come across this error myself and just happened across this issue. A request for @derjust - can we rename this issue something like "No field annotated with interface org.springframework.data.annotation.Id found!" because it's likely other people have hit this problem but won't spot this issue because of the title.

The problem is that if you're using a hash key and a range key you have to design the entity class, and an "id" or primary key class, and do it in a particular way or you get this error message that doesn't really explain the problem. At first I presumed that spring-data-dynamodb simply doesn't support the hash and range keys together like you can with the AWS SDK. When I had a look at the sample code in the older repo, I found that there was an example. The entity and "id" class pattern is a bit odd, but it works.

To anyone seeing this error, make sure you're doing the following:

- You need a specialized class for your primary key. It needs to implement Serializable and will have the fields, getters, and setters for your hash key field and range key field.
- In your entity class, _instead of_ the hash key field and range key field, you have a field that is an instance of the specialized key class mentioned above. You must annotate that field with Spring's `@Id` annotation, but do not provide a getter or setter.
- Also in your entity class, do provide a getter and setter for your hash key field and range key field, _even though your entity doesn't have those fields_. You pass those through to the corresponding method on your primary key field.
- Make sure to lazy-create your primary key field in the hash key and range key setters in the entity.
- The hash key and range key getters in both your entity class and primary key class have to be annotated with `@DynamoDBHashKey` and `@DynamoDBRangeKey`, respectively. Yes, this is redundant.
- Make sure that your repo uses the primary key class for the "ID" class, otherwise you'll get another weird error about something not being an instance of the right class.

Do all of the above and the hash-key/range-ky combo will work properly. See the following two code examples, from the older spring-data-dynamodb repo, as a reference:

[Entity class](https://github.com/michaellavelle/spring-data-dynamodb-demo/blob/master/src/main/java/org/socialsignin/springframework/data/dynamodb/demo/domain/Reply.java)
[Entity id class](https://github.com/michaellavelle/spring-data-dynamodb-demo/blob/master/src/main/java/org/socialsignin/springframework/data/dynamodb/demo/domain/ReplyId.java)

**Comment by rwhitsell** [comment] 2016-04-13 04:49
This isn't a bug. There's a particular way you have to structure your entity class and "id" class for it to work in spring-data-dynamodb.

I've commented in the corresponding issue in the new repo:  https://github.com/derjust/spring-data-dynamodb/issues/24

**Comment by derjust** [comment] 2016-04-13 10:06
I will try to provide a better message. Chances are that this is generated by Spring itself thus there is little influence by us. 
But I try. Thanks for the exhaustive list.

**Comment by rwhitsell** [comment] 2016-04-13 19:50
I wouldn't worry about the error message, and for that matter, don't worry about renaming this issue. I think you can close this issue; there isn't a bug, just some odd behavior. The software works once the programmer determines the "recipe", which is available by looking at the example code.

The challenge is that Spring-Data has its own annotations and way of doing things, the AWS SDK has its own annotations and way of doing things, and spring-data-dynamodb is an integration of two. It isn't surprising that occasionally something strange happens. An exhaustive examination of all the edge- and error-cases is tough to do without a sizable team and plenty of time. You're doing great, thanks for keeping up the repo and keeping up this project.

If I have time to contribute to the code base, I'll check in with you. I'm actively using this project at the moment.

**Comment by derjust** [comment] 2016-04-14 13:36
> The challenge is that Spring-Data has its own annotations and way of doing things, the AWS SDK has its own annotations and way of doing things, and spring-data-dynamodb is an integration of two. 

yeah that's the fun for this issue.
Having a better error message on the other hand for sure would direct people in the right direction (as the existing one is somewhat non-conclusive)

Thanks!

**Comment by rwhitsell** [comment] 2016-04-14 16:40
Yeah, good point. Mysterious error messages don't help.

The pattern required for the hash key/range key combination is a bit odd. Having the same getters and setters with AWS annotations in both the entity _and_ it's embedded "Id" class is what threw me off because it's redundant. If you got rid of the requirement to have hash- and range-key methods/annotations in the entity class _when_ there's an embedded "Id" class it would make more sense (and be backward-compatible for people who've had to do it the current way).

Just an idea.

**Comment by Cybertran** [comment] 2018-03-20 13:35
hi @derjust i am also getting same issue 
 No field annotated with interface org.springframework.data.annotation.Id found!
Here is my Entity
`@Data
@DynamoDBTable(tableName = "user")
public class User{
 @DynamoDBHashKey(attributeName = "roleNumber")
   private String roleNumber

    @DynamoDBAttribute(attributeName = "correlationId")
    private String correlationId;

    @DynamoDBAttribute(attributeName = "carrier")
    private String name;
}

@Configuration
@EnableDynamoDBRepositories("org.myapp.dynamo")
public class DynamoDBConfig {

    @Value("${ENV}")
    private String environment;


    Supplier<AWSCredentialsProvider> credentialSupplier = ()->{
        return new AWSCredentialsProviderChain(new EnvironmentVariableCredentialsProvider(),
                new SystemPropertiesCredentialsProvider(),
                new ProfileCredentialsProvider(),
                new InstanceProfileCredentialsProvider(false));

    };

//    @Bean
//    public DynamoDBOperations dynamoDBOperations() {
//        final DynamoDBTemplate dynamoDBTemplate = new DynamoDBTemplate(amazonDynamoDB());
//        final DynamoDBMapperConfig.TableNameOverride tableNameOverride = DynamoDBMapperConfig.TableNameOverride .withTableNamePrefix(environment);
//        dynamoDBTemplate.setApplicationContext();
//
//        return dynamoDBTemplate;
//    }

    @Bean
    public AmazonDynamoDB amazonDynamoDB() {
        AmazonDynamoDB amazonDynamoDB = AmazonDynamoDBClientBuilder.standard()
                .withRegion(System.getenv("AWS_REGION"))
                .withCredentials(credentialSupplier.get())
                .build();

        return amazonDynamoDB;
    }
    
}

@EnableScan
public interface UserRepository extends CrudRepository<User,String> {


    User findByCorrelationId(@Param(value="correlationId") String  correlationId);


}

`
i am using below dependency in my pom

`
   <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>1.11.297</version>
        </dependency>
        <dependency>
            <groupId>com.github.derjust</groupId>
            <artifactId>spring-data-dynamodb</artifactId>
            <version>4.5.5</version>
        </dependency>
`
THere is no documentation what @EnableScan does 
Please help me where i am doing wrong with configuration

**Closed** 2020-07-13 21:47 UTC
