### ISSUE TITLE
How to use DynamoDBIndexHashKey and DynamoDBIndexRangeKey

### ISSUE THREAD

**Issue by jAddict7** [michaellavelle/spring-data-dynamodb#31] opened 2014-06-11 14:35 UTC
I have created a GSI hash and key index in DynamoDB in the name "description-name-index" and I like to sort its data using range key by findBy of hash key. Here is my test code,
**Domain Class**
        @DynamoDBTable(tableName = "test")
        public class Test implements Serializable{

```
private static final long serialVersionUID = 1L;

private String id;
private String description;
private String name;

@DynamoDBIndexHashKey(attributeName="description")
public String getDescription() {
    return tesId;
}

public void setDescription(String description) {
    this.setDescription(description);;
}

@DynamoDBIndexRangeKey(attributeName="name")
public String getName() {
    return name;
}

public void setName(String name) {
    this.setName(name);
}

@DynamoDBHashKey(attributeName="id")
public String getId() {
    return id;
}

public void setId(String id) {
    this.id = id;
}

    }
```

and tries to fetch and sort data using **findByDescriptionOrderByNameDesc(@Param("decription") String description, Pageable pageable)** and also I tried using @Id and placed index hash and range key in a class but all in vain. Am getting 500 Internal Error but not throwing any message too. Is there any way to use GSI hash and range pair and sort them. Thank you.

**Comment by derjust** [comment] 2016-01-25 03:19
Duplicate of #11

As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.

**Comment by derjust** [comment] 2016-02-10 05:18
Check out https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys

**Closed** 2020-07-13 21:47 UTC
